### PR TITLE
251 check the good functionality of offline mode

### LINKED ISSUE #251: Check the good functionality of offline mode
Test the offline mode. Replace Loading texts by "offline mode" or "no connection". No crash is permitted.

Loading texts appears at sevearl places:
* Chat screen
* Follower
* Following

### PR DESCRIPTION
**Pull request by SamBachmann**
Here's what I have implemented and fix in this PR:

* Changed "loading" texts for "currently offline" when in offline mode
* Little UI changes to have a clean GUI
* Testing the offline mode on my device and make changes accordlingly
* Supress magic values from Events 

Once merged this PR will close #251

### CODE REVIEW

File: app/src/main/java/com/github/se/gatherspot/ui/topLevelDestinations/Chats.kt [hunk 1]
```diff
@@ -82,10 +86,10 @@ fun Chats(viewModel: ChatsListViewModel, nav: NavigationActions) {
         when {
           events.isEmpty() -> {
             Box(
-                modifier = Modifier.fillMaxWidth().padding(paddingValues),
-                contentAlignment = Alignment.TopStart) {
+                modifier = Modifier.fillMaxSize().padding(paddingValues),
+                contentAlignment = Alignment.Center) {
                   Text(
-                      text = "No chatting group found...",
+                      text = if (isOnline) "Loading..." else "Your device is currently offline.",
```
Comment (mmalonga) [inline app/src/main/java/com/github/se/gatherspot/ui/topLevelDestinations/Chats.kt:92]: "Loading..." --> "No chatting group found..."

**Review by mmalonga — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/github/se/gatherspot/ui/topLevelDestinations/Chats.kt (hunk 1 above)
Comment (SamBachmann) [reply app/src/main/java/com/github/se/gatherspot/ui/topLevelDestinations/Chats.kt:92]: Sure, I will change that

**Review by mmalonga — APPROVED** [review]
Vwery nice !
